@baseUrl = http://localhost:4000/api

###

POST {{baseUrl}}/verification-emails
Content-Type: application/json

{
  "email": "user@example.com",
  "code_challenge": "E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM"
}

